### ISSUE TITLE
Mounting hardware for Pi + Blade

### ISSUE THREAD

**Issue by stefangordon** [CatalystCode/cell-sar#2]

**Comment by mzxgiant** [comment]
The 3D-printed case we have is a great design, and we just need to print a "final" case that's a little cleaner than the prototype case we're using now. Also we're using a 6" http://www.usbfirewire.com/parts/rr-albl-xxgr.html to link the RPi and the bladeRF, which ended up being the perfect size.

**Comment by anthturner** [comment]
Closing since this project is now out of scope and is unlikely to be revisited in the future. Hopefully the information contained in these issues can help someone in the future who looks to implement this.
