### ISSUE TITLE
Antenna wiring/mounting

### ISSUE THREAD

**Issue by stefangordon** [CatalystCode/cell-sar#3]

**Comment by mzxgiant** [comment]
I really like our design during the first test. Maybe we can 3D-print clips to hold those antennas on a bit better than the zip-ties, but having the flexibility in the air to change the radiation pattern of the sensor is *huge* (especially if we can have per-leg control of the landing gear, maybe?). Thoughts?

**Comment by mzxgiant** [comment]
Based on some more recent testing, I'm convinced that using the antennas as the third leg of a triangle against the landing gear is the best move for us, as it seems to have issues generating an adequate field when they're closer to the gimbal mount. We should address the servo calibration accordingly.

**Comment by anthturner** [comment]
Closing since this project is now out of scope and is unlikely to be revisited in the future. Hopefully the information contained in these issues can help someone in the future who looks to implement this.
