### ISSUE TITLE
Build and commit flight safety checklist

### ISSUE THREAD

**Issue by stefangordon** [CatalystCode/cell-sar#7]
Since we are flying commercially we have to follow the rules, so lets take DJI's recommended flight safety checklist, modify it with stuff related to our SAR equipment, and commit to to our repository.

**Comment by mzxgiant** [comment]
I'm not sure how long this list is supposed to be, but for the Matrice 100, here's the relevant section in the user manual:

> Pre-Flight Checklist
> 1. The remote controller, Intelligent Flight Battery, and your mobile device are fully charged.
> 2. Propellers are mounted correctly and firmly.
> 3. Motors start properly and are functioning as normal.
> 4. The DJI GO app is connected to the aircraft.
https://www.manualslib.com/manual/1091851/Dji-Matrice-100.html?page=56#manual

**Comment by mzxgiant** [comment]
Another example: https://kittyhawk.io/public-checklists/4081

**Comment by anthturner** [comment]
Closing since this project is now out of scope and is unlikely to be revisited in the future. Hopefully the information contained in these issues can help someone in the future who looks to implement this.
